benchmark:
  name: "navier_stokes_2d"
  dataset: "NavierStokes_V1e-5_N1200_T20"
  invariant: "global_vorticity"
  geometry: "periodic_grid"

paths:
  root_dir: "data/NavierStokes_V1e-5_N1200_T20"

data:
  ntrain: 1000
  ntest: 200
  T_in: 10
  T_out: 10
  downsamplex: 1
  downsampley: 1
