benchmark:
  name: "pipe_2d"
  dataset: "Pipe"
  invariant: "unconstrained_flow_response"
  geometry: "structured_grid"

paths:
  root_dir: "data/pipe"

data:
  ntrain: 1000
  ntest: 200
  target_channel: 0 # [0: ux, 1: uy, 2: p]
  downsamplex: 4
  downsampley: 4
  normalize: true
  norm_type: "UnitTransformer"
