benchmark:
  name: "elasticity_2d"
  dataset: "Elasticity"
  invariant: "incompressible_deviatoric_von_mises"
  geometry: "unstructured_point_cloud"

paths:
  root_dir: "data/elasticity"

data:
  ntrain: 1000
  ntest: 200
  normalize: true
  norm_type: "UnitTransformer"
