"""CLI entrypoint for the report build system.

Usage:
    python -m scripts.reporting.build                              # all artifacts
    python -m scripts.reporting.build --chapter 5                  # one chapter
    python -m scripts.reporting.build --name cv_constrained        # one artifact
    python -m scripts.reporting.build --output-dir ../fyp_report/generated
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from scripts.reporting.core.emit_tex import write_artifact
    from scripts.reporting.core.types import MetricFileRef, ReportArtifact, RunRef
    from scripts.reporting.registry import ARTIFACTS
else:
    from .core.emit_tex import write_artifact
    from .core.types import MetricFileRef, ReportArtifact, RunRef
    from .registry import ARTIFACTS


def _repo_root() -> Path:
    here = Path(__file__).resolve()
    for p in [here, *here.parents]:
        if (p / "pyproject.toml").exists():
            return p
    raise RuntimeError("could not locate repo root (no pyproject.toml ancestor)")


def _rel(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _test_command_for_run(run: RunRef, repo_root: Path) -> str | None:
    run_dir = run.resolve(repo_root)
    config_path = run_dir / "resolved_config.yaml"
    checkpoint_path = run_dir / "best.pt"
    if not checkpoint_path.exists():
        checkpoint_path = run_dir / "latest.pt"
    if not config_path.exists() or not checkpoint_path.exists():
        return None
    return (
        "test: "
        f"--config {_rel(config_path, repo_root)} "
        f"--checkpoint {_rel(checkpoint_path, repo_root)}"
    )


def _write_missing_runs_file(
    path: Path,
    selected: list[ReportArtifact],
    artifact_results: dict[str, list],
    repo_root: Path,
) -> int:
    seen_runs: set[str] = set()
    lines = [
        "# Generated by scripts/reporting/build.py",
        "# Feed this file to scripts/run_batch.sh or scripts/hpc/runner.sh via RUNS_FILE.",
        "# Blank lines and comments are ignored.",
        "",
    ]
    command_count = 0
    for artifact in selected:
        results = artifact_results.get(artifact.name, [])
        for row, result in zip(artifact.rows, results, strict=False):
            if result.ok:
                continue
            if isinstance(row.run, RunRef):
                if row.run.path in seen_runs:
                    continue
                seen_runs.add(row.run.path)
                command = _test_command_for_run(row.run, repo_root)
                if command is None:
                    lines.append(
                        f"# {artifact.name} {result.macro}: no resolved_config.yaml "
                        f"and checkpoint found under {row.run.path}"
                    )
                    continue
                lines.append(f"# {artifact.name}: {row.run.path}")
                lines.append(command)
                lines.append("")
                command_count += 1
            elif isinstance(row.run, MetricFileRef):
                lines.append(
                    f"# {artifact.name} {result.macro}: generated metric source "
                    f"{row.run.path}; run python -m scripts.reporting.compute_ch5"
                )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n")
    return command_count


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="reporting.build")
    parser.add_argument(
        "--chapter", type=int, default=None, help="only build artifacts for this chapter"
    )
    parser.add_argument(
        "--name", type=str, default=None, help="only build the artifact with this name"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="root directory for generated files (default: artifacts/report/)",
    )
    parser.add_argument(
        "--write-missing-runs",
        type=Path,
        default=None,
        help="write a RUNS_FILE with test commands for missing RunRef metrics",
    )
    args = parser.parse_args(argv)

    repo_root = _repo_root()
    output_dir = args.output_dir or (repo_root / "artifacts/report")
    output_dir = output_dir.resolve()

    selected = [
        a
        for a in ARTIFACTS
        if (args.chapter is None or a.chapter == args.chapter)
        and (args.name is None or a.name == args.name)
    ]
    if not selected:
        print("no artifacts matched filters", file=sys.stderr)
        return 1

    print(f"output dir: {output_dir}")
    n_ok = n_missing = 0
    artifact_results = {}
    for artifact in selected:
        if artifact.kind != "tex_macros":
            print(f"  skip (kind={artifact.kind}): {artifact.name}")
            continue
        results = write_artifact(artifact, repo_root, output_dir)
        artifact_results[artifact.name] = results
        ok = sum(r.ok for r in results)
        missing = len(results) - ok
        n_ok += ok
        n_missing += missing
        status = "OK" if missing == 0 else f"{missing} TBD"
        print(f"  {artifact.name:<20} {ok}/{len(results)} cells  [{status}]")
        for r in results:
            if not r.ok:
                print(f"    - {r.macro}: {r.source}")

    print(f"\ntotal: {n_ok} resolved, {n_missing} TBD")
    if args.write_missing_runs is not None:
        runs_path = args.write_missing_runs
        if not runs_path.is_absolute():
            runs_path = output_dir / runs_path
        command_count = _write_missing_runs_file(
            runs_path, selected, artifact_results, repo_root
        )
        print(f"missing runs file: {runs_path} ({command_count} commands)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
