"""CLI entrypoint for the report build system.

Usage:
    python -m scripts.reporting.build                              # all artifacts
    python -m scripts.reporting.build --chapter 5                  # one chapter
    python -m scripts.reporting.build --name cv_constrained        # one artifact
    python -m scripts.reporting.build --output-dir ../fyp_report
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from scripts.reporting.core.emit_tex import write_artifact
    from scripts.reporting.core.types import MetricFileRef, ReportArtifact, RunRef
    from scripts.reporting.registry import ARTIFACTS
    from scripts.reporting.registry.ch5 import (
        cost_diagnostic_runs,
        diagnose_command_for_run,
        write_cost_metrics,
        write_provenance_table,
    )
    from scripts.reporting.registry.ns_report import (
        diagnose_command_for_ns_run,
        ns_cost_diagnostic_runs,
        write_ns_cost_metrics,
    )
else:
    from .core.emit_tex import write_artifact
    from .core.types import MetricFileRef, ReportArtifact, RunRef
    from .registry import ARTIFACTS
    from .registry.ch5 import (
        cost_diagnostic_runs,
        diagnose_command_for_run,
        write_cost_metrics,
        write_provenance_table,
    )
    from .registry.ns_report import (
        diagnose_command_for_ns_run,
        ns_cost_diagnostic_runs,
        write_ns_cost_metrics,
    )


def _repo_root() -> Path:
    here = Path(__file__).resolve()
    for p in [here, *here.parents]:
        if (p / "pyproject.toml").exists():
            return p
    raise RuntimeError("could not locate repo root (no pyproject.toml ancestor)")


def _rel(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _test_command_for_run(run: RunRef, repo_root: Path) -> str | None:
    run_dir = run.resolve(repo_root)
    config_path = run_dir / "resolved_config.yaml"
    checkpoint_path = run_dir / "best.pt"
    if not checkpoint_path.exists():
        checkpoint_path = run_dir / "latest.pt"
    if not config_path.exists() or not checkpoint_path.exists():
        return None
    return (
        "test: "
        f"--config {_rel(config_path, repo_root)} "
        f"--checkpoint {_rel(checkpoint_path, repo_root)}"
    )


def _reporting_fingerprint(selected: list[ReportArtifact]) -> str:
    payload = []
    for artifact in selected:
        rows = []
        for row in artifact.rows:
            if isinstance(row.run, RunRef):
                run = {"type": "run", "path": row.run.path}
            elif isinstance(row.run, MetricFileRef):
                run = {"type": "metric_file", "path": row.run.path}
            else:
                run = None
            rows.append(
                {
                    "run": run,
                    "metric_key": row.metric_key,
                    "macro": row.macro,
                    "format": row.format,
                    "literal": row.literal,
                }
            )
        payload.append(
            {
                "name": artifact.name,
                "chapter": artifact.chapter,
                "kind": artifact.kind,
                "output_subpath": artifact.output_subpath,
                "rows": rows,
            }
        )
    encoded = json.dumps(payload, sort_keys=True, default=list).encode()
    return hashlib.sha256(encoded).hexdigest()[:16]


def _write_missing_runs_file(
    path: Path,
    selected: list[ReportArtifact],
    artifact_results: dict[str, list],
    repo_root: Path,
    *,
    chapter: int | None = None,
    name: str | None = None,
    mode: str = "missing",
) -> int:
    seen_test_runs: set[str] = set()
    seen_diagnose_runs: set[str] = set()
    lines = [
        "# Generated by scripts/reporting/build.py",
        f"# reporting_fingerprint: {_reporting_fingerprint(selected)}",
        f"# reporting_chapter: {chapter if chapter is not None else 'all'}",
        f"# reporting_name: {name if name is not None else 'all'}",
        f"# runfile_mode: {mode}",
        "# Feed this file to scripts/run_batch.sh or scripts/hpc/runner.sh via RUNS_FILE.",
        "# Blank lines and comments are ignored.",
        "",
    ]
    command_count = 0
    cost_comment_written = False
    cost_runs_written = False
    ns_cost_comment_written = False
    ns_cost_runs_written = False
    for artifact in selected:
        results = artifact_results.get(artifact.name, [])
        for row, result in zip(artifact.rows, results, strict=False):
            if mode == "missing" and result.ok:
                continue
            if isinstance(row.run, RunRef):
                if row.run.path in seen_test_runs:
                    continue
                seen_test_runs.add(row.run.path)
                command = _test_command_for_run(row.run, repo_root)
                if command is None:
                    lines.append(
                        f"# {artifact.name} {result.macro}: no resolved_config.yaml "
                        f"and checkpoint found under {row.run.path}"
                    )
                    continue
                lines.append(f"# {artifact.name}: {row.run.path}")
                lines.append(command)
                lines.append("")
                command_count += 1
            elif isinstance(row.run, MetricFileRef):
                if row.run.path == "ch5_gt_metrics.yaml":
                    lines.append(
                        f"# {artifact.name} {result.macro}: GT data diagnostics; "
                        "run python -m scripts.reporting.compute_ch5"
                    )
                elif row.run.path == "ch5_cost_metrics.yaml":
                    if not cost_comment_written:
                        lines.append(
                            "# cv_cost: run-local diagnostics; generated by scripts/diagnose.py"
                        )
                        cost_comment_written = True
                    if not cost_runs_written:
                        for run in cost_diagnostic_runs():
                            if run.path in seen_diagnose_runs:
                                continue
                            seen_diagnose_runs.add(run.path)
                            command = diagnose_command_for_run(run, repo_root)
                            if command is None:
                                lines.append(
                                    f"# cv_cost: no resolved_config.yaml and checkpoint "
                                    f"found under {run.path}"
                                )
                                continue
                            lines.append(f"# cv_cost: {run.path}")
                            lines.append(command)
                            lines.append("")
                            command_count += 1
                        cost_runs_written = True
                elif row.run.path == "ch4_ns_cost_metrics.yaml":
                    if not ns_cost_comment_written:
                        lines.append(
                            "# ns_cost/ns_hook: run-local diagnostics; "
                            "generated by scripts/diagnose.py"
                        )
                        ns_cost_comment_written = True
                    if not ns_cost_runs_written:
                        for run in ns_cost_diagnostic_runs():
                            if run.path in seen_diagnose_runs:
                                continue
                            seen_diagnose_runs.add(run.path)
                            command = diagnose_command_for_ns_run(run, repo_root)
                            if command is None:
                                lines.append(
                                    f"# ns_cost: no resolved_config.yaml and checkpoint "
                                    f"found under {run.path}"
                                )
                                continue
                            lines.append(f"# ns_cost: {run.path}")
                            lines.append(command)
                            lines.append("")
                            command_count += 1
                        ns_cost_runs_written = True
                else:
                    lines.append(
                        f"# {artifact.name} {result.macro}: generated metric source "
                        f"{row.run.path}; not produced by the test batch runner"
                    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n")
    return command_count


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="reporting.build")
    parser.add_argument(
        "--chapter", type=int, default=None, help="only build artifacts for this chapter"
    )
    parser.add_argument(
        "--name", type=str, default=None, help="only build the artifact with this name"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="root directory for generated files (default: artifacts/report/)",
    )
    parser.add_argument(
        "--write-missing-runs",
        type=Path,
        default=Path("missing_runs.txt"),
        help=(
            "write a RUNS_FILE with test commands for missing RunRef metrics "
            "(default: output-dir/missing_runs.txt)"
        ),
    )
    parser.add_argument(
        "--no-write-missing-runs",
        action="store_true",
        help="do not write the missing-runs RUNS_FILE",
    )
    parser.add_argument(
        "--runfile-mode",
        choices=("missing", "all"),
        default="missing",
        help="which RunRef rows to include when writing a runfile",
    )
    parser.add_argument(
        "--print-fingerprint",
        action="store_true",
        help="print the selected reporting registry fingerprint and exit",
    )
    args = parser.parse_args(argv)

    repo_root = _repo_root()
    output_dir = args.output_dir or (repo_root / "artifacts/report")
    output_dir = output_dir.resolve()

    selected = [
        a
        for a in ARTIFACTS
        if (args.chapter is None or a.chapter == args.chapter)
        and (args.name is None or a.name == args.name)
    ]
    if not selected:
        print("no artifacts matched filters", file=sys.stderr)
        return 1
    if args.print_fingerprint:
        print(_reporting_fingerprint(selected))
        return 0

    print(f"output dir: {output_dir}")
    includes_ch5 = any(a.chapter == 5 for a in selected)
    if includes_ch5:
        cost_path = write_cost_metrics(repo_root, output_dir)
        table_path = write_provenance_table(repo_root, output_dir)
        print(f"  wrote cost metrics: {cost_path}")
        print(f"  wrote provenance table: {table_path}")
    includes_ns_cost = any(a.name in {"ns_cost", "ns_hook"} for a in selected)
    if includes_ns_cost:
        ns_cost_path = write_ns_cost_metrics(repo_root, output_dir)
        print(f"  wrote ns cost metrics: {ns_cost_path}")

    n_ok = n_missing = 0
    artifact_results = {}
    for artifact in selected:
        if artifact.kind != "tex_macros":
            print(f"  skip (kind={artifact.kind}): {artifact.name}")
            continue
        results = write_artifact(artifact, repo_root, output_dir)
        artifact_results[artifact.name] = results
        ok = sum(r.ok for r in results)
        missing = len(results) - ok
        n_ok += ok
        n_missing += missing
        status = "OK" if missing == 0 else f"{missing} TBD"
        print(f"  {artifact.name:<20} {ok}/{len(results)} cells  [{status}]")
        for r in results:
            if not r.ok:
                print(f"    - {r.macro}: {r.source}")

    print(f"\ntotal: {n_ok} resolved, {n_missing} TBD")
    if not args.no_write_missing_runs:
        runs_path = args.write_missing_runs
        if not runs_path.is_absolute():
            runs_path = output_dir / runs_path
        command_count = _write_missing_runs_file(
            runs_path,
            selected,
            artifact_results,
            repo_root,
            chapter=args.chapter,
            name=args.name,
            mode=args.runfile_mode,
        )
        print(f"missing runs file: {runs_path} ({command_count} commands)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
