"""Chapter 5 run provenance and cost accounting artifacts.

The report tables should describe the runs on disk, not a separately maintained
spreadsheet. This module reads resolved configs and optional run-local
``diagnostics.yaml`` files, then emits report-only artifacts under
``artifacts/report`` or ``../fyp_report/generated``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from .registry.ch5 import (
    DARCY_BL,
    DARCY_DIRICHLET_HC,
    DARCY_FLUX_HC,
    ELAS_BL,
    ELAS_HC,
    NS_BL,
    NS_HC,
    PIPE_BL,
    PIPE_HC,
    PLAS_BL,
    PLAS_HC,
)
from .core.types import RunRef


@dataclass(frozen=True)
class Ch5RunSpec:
    label: str
    role: str
    run: RunRef


@dataclass(frozen=True)
class Ch5CostSpec:
    key: str
    constrained: RunRef
    baseline: RunRef


PROVENANCE_RUNS: tuple[Ch5RunSpec, ...] = (
    Ch5RunSpec("Navier-Stokes", "Baseline", NS_BL),
    Ch5RunSpec("Navier-Stokes", "Constrained", NS_HC),
    Ch5RunSpec("Darcy", "Baseline", DARCY_BL),
    Ch5RunSpec("Darcy Dirichlet", "Constrained", DARCY_DIRICHLET_HC),
    Ch5RunSpec("Darcy Flux", "Constrained", DARCY_FLUX_HC),
    Ch5RunSpec("Pipe", "Baseline", PIPE_BL),
    Ch5RunSpec("Pipe Stream", "Constrained", PIPE_HC),
    Ch5RunSpec("Elasticity", "Baseline", ELAS_BL),
    Ch5RunSpec("Elasticity", "Constrained", ELAS_HC),
    Ch5RunSpec("Plasticity", "Baseline", PLAS_BL),
    Ch5RunSpec("Plasticity", "Constrained", PLAS_HC),
)


COST_SPECS: tuple[Ch5CostSpec, ...] = (
    Ch5CostSpec("ns", NS_HC, NS_BL),
    Ch5CostSpec("darcy_dirichlet", DARCY_DIRICHLET_HC, DARCY_BL),
    Ch5CostSpec("darcy_flux", DARCY_FLUX_HC, DARCY_BL),
    Ch5CostSpec("pipe_wall", PIPE_HC, PIPE_BL),
    Ch5CostSpec("pipe_stream", PIPE_HC, PIPE_BL),
    Ch5CostSpec("elasticity", ELAS_HC, ELAS_BL),
    Ch5CostSpec("plasticity", PLAS_HC, PLAS_BL),
)


def effective_training_samples(cfg: dict[str, Any]) -> int:
    ntrain = int((cfg.get("data") or {}).get("ntrain", 1000))
    val_size = int((cfg.get("training") or {}).get("val_size", 0))
    if val_size <= 0:
        return ntrain
    return max(ntrain - min(max(val_size, 1), ntrain - 1), 1)


def resolve_run_config(repo_root: Path, run: RunRef) -> tuple[Path, dict[str, Any] | None]:
    run_dir = run.resolve(repo_root)
    cfg_path = run_dir / "resolved_config.yaml"
    if not cfg_path.exists():
        return run_dir, None
    return run_dir, yaml.safe_load(cfg_path.read_text()) or {}


def _diagnostics_path(repo_root: Path, run: RunRef) -> Path:
    return run.resolve(repo_root) / "diagnostics.yaml"


def _load_diagnostics(repo_root: Path, run: RunRef) -> dict[str, Any] | None:
    path = _diagnostics_path(repo_root, run)
    if not path.exists():
        return None
    return yaml.safe_load(path.read_text()) or {}


def _run_model_name(cfg: dict[str, Any]) -> str:
    experiment = cfg.get("experiment") or {}
    model = cfg.get("model") or {}
    return str(experiment.get("backbone") or model.get("backbone") or "?")


def _run_constraint_name(cfg: dict[str, Any]) -> str:
    experiment = cfg.get("experiment") or {}
    return str(experiment.get("constraint") or "none")


def _run_epochs(cfg: dict[str, Any]) -> int:
    return int((cfg.get("training") or {}).get("num_epochs", 0))


def _tex_escape(value: str) -> str:
    return (
        value.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
    )


def _tt_path(path: str) -> str:
    return r"\texttt{\detokenize{" + path + "}}"


def render_provenance_table(repo_root: Path) -> str:
    rows: list[str] = []
    for spec in PROVENANCE_RUNS:
        run_dir, cfg = resolve_run_config(repo_root, spec.run)
        if cfg is None:
            model = epochs = samples = constraint = r"\textit{TBD}"
        else:
            model = _tex_escape(_run_model_name(cfg))
            constraint = _tex_escape(_run_constraint_name(cfg))
            epochs = str(_run_epochs(cfg))
            samples = str(effective_training_samples(cfg))
        rows.append(
            "        "
            + " & ".join(
                [
                    _tex_escape(spec.label),
                    _tex_escape(spec.role),
                    model,
                    constraint,
                    str(epochs),
                    str(samples),
                    _tt_path(spec.run.path if cfg is not None else str(run_dir)),
                ]
            )
            + r" \\"
        )

    body = "\n".join(rows)
    return rf"""% Generated by scripts/reporting/build.py
% Artifact: ch5_run_provenance  (chapter 5)

\begin{{table}}[htbp]
    \centering
    \small
    \caption{{Source runs for the Chapter~5 baseline and constrained model results.}}
    \label{{tab:ch5_run_provenance}}
    \resizebox{{\linewidth}}{{!}}{{%
    \begin{{tabular}}{{llllrrl}}
        \toprule
        Result & Role & Model & Constraint & Epochs & Train samples & Run directory \\
        \midrule
{body}
        \bottomrule
    \end{{tabular}}
    }}
\end{{table}}
"""


def write_provenance_table(repo_root: Path, output_dir: Path) -> Path:
    path = output_dir / "tables" / "ch5_run_provenance.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_provenance_table(repo_root))
    return path


def _cost_number(diagnostics: dict[str, Any], key: str) -> float | None:
    cost = diagnostics.get("cost") or {}
    value = cost.get(key)
    return float(value) if value is not None else None


def _overhead(constrained: float | None, baseline: float | None) -> float | None:
    if constrained is None or baseline is None:
        return None
    return constrained - baseline


def compute_cost_metrics(repo_root: Path) -> tuple[dict[str, float], list[str]]:
    metrics: dict[str, float] = {}
    warnings: list[str] = []

    for spec in COST_SPECS:
        constrained_diag = _load_diagnostics(repo_root, spec.constrained)
        baseline_diag = _load_diagnostics(repo_root, spec.baseline)
        if constrained_diag is None:
            warnings.append(f"missing diagnostics: {spec.constrained.path}/diagnostics.yaml")
        if baseline_diag is None:
            warnings.append(f"missing diagnostics: {spec.baseline.path}/diagnostics.yaml")
        if constrained_diag is None or baseline_diag is None:
            continue

        params_overhead = _overhead(
            _cost_number(constrained_diag, "trainable_params"),
            _cost_number(baseline_diag, "trainable_params"),
        )
        flops_overhead = _overhead(
            _cost_number(constrained_diag, "epoch_flops"),
            _cost_number(baseline_diag, "epoch_flops"),
        )
        if params_overhead is not None:
            metrics[f"{spec.key}/params_overhead"] = params_overhead
        if flops_overhead is not None:
            metrics[f"{spec.key}/flops_overhead"] = flops_overhead

    return metrics, warnings


def write_cost_metrics(repo_root: Path, output_dir: Path) -> Path:
    metrics, warnings = compute_cost_metrics(repo_root)
    path = output_dir / "metrics" / "ch5_cost_metrics.yaml"
    path.parent.mkdir(parents=True, exist_ok=True)
    payload: dict[str, Any] = {"metrics": metrics}
    if warnings:
        payload["warnings"] = sorted(set(warnings))
    path.write_text(yaml.safe_dump(payload, sort_keys=True))
    return path


def diagnose_command_for_run(run: RunRef, repo_root: Path) -> str | None:
    run_dir = run.resolve(repo_root)
    config_path = run_dir / "resolved_config.yaml"
    checkpoint_path = run_dir / "best.pt"
    if not checkpoint_path.exists():
        checkpoint_path = run_dir / "latest.pt"
    if not config_path.exists() or not checkpoint_path.exists():
        return None
    return (
        "diagnose: "
        f"--config {config_path.relative_to(repo_root).as_posix()} "
        f"--checkpoint {checkpoint_path.relative_to(repo_root).as_posix()} "
        "--write-yaml"
    )


def cost_diagnostic_runs() -> tuple[RunRef, ...]:
    seen: set[str] = set()
    runs: list[RunRef] = []
    for spec in COST_SPECS:
        for run in (spec.baseline, spec.constrained):
            if run.path not in seen:
                seen.add(run.path)
                runs.append(run)
    return tuple(runs)
