data:
  ntrain: 8
  ntest: 200
  downsamplex: 20
  downsampley: 20

training:
  batch_size: 1
  val_size: 2
  num_epochs: 1
  seed: 42

evaluation:
  batch_size: 1

wandb_logging:
  wandb: false
  log_every: 1
  image_log_every: null

optuna:
  num_trials: 2
