data:
  ntrain: 128
  ntest: 200
  downsamplex: 10
  downsampley: 10

training:
  batch_size: 1
  val_size: 16
  num_epochs: 10
  seed: 42

evaluation:
  batch_size: 1

wandb_logging:
  wandb: false
  log_every: 10
  image_log_every: null

optuna:
  num_trials: 10
