from __future__ import annotations

import datetime as dt
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .collect import MissingMetric, MissingRun, get_metric, load_run
from .types import ReportArtifact


TBD = r"\textit{TBD}"


@dataclass
class CellResult:
    macro: str
    value: str
    source: str  # human-readable: run path or "literal" or "missing: <reason>"
    ok: bool


def _format_scientific(value: float, fmt: str) -> str:
    """Format a float and rewrite Python's 'e' notation as LaTeX \\times 10^{...}.

    The result is wrapped in \\ensuremath{} so the macro can be used in either
    text or math mode in the chapter tables.
    """
    s = fmt.format(value)
    m = re.fullmatch(r"(-?\d+(?:\.\d+)?)[eE]([+-]?)0*(\d+)", s)
    if not m:
        return s
    mantissa, sign, exp_digits = m.groups()
    exp = ("-" if sign == "-" else "") + (exp_digits or "0")
    return rf"\ensuremath{{{mantissa}\times 10^{{{exp}}}}}"


def _git_sha(repo_root: Path) -> str:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=repo_root, text=True
        )
        return out.strip()
    except Exception:
        return "unknown"


def render_macro_table(
    artifact: ReportArtifact, repo_root: Path
) -> tuple[str, list[CellResult]]:
    assert artifact.kind == "tex_macros"
    results: list[CellResult] = []
    for row in artifact.rows:
        if row.literal is not None:
            results.append(
                CellResult(row.macro, row.literal, source="literal", ok=True)
            )
            continue
        if row.run is None or row.metric_key is None:
            results.append(
                CellResult(row.macro, TBD, source="missing: no run/metric", ok=False)
            )
            continue
        try:
            data = load_run(row.run, repo_root)
            value = get_metric(data, row.metric_key)
        except MissingRun as e:
            results.append(CellResult(row.macro, TBD, source=f"missing: {e}", ok=False))
            continue
        except MissingMetric as e:
            results.append(
                CellResult(row.macro, TBD, source=f"missing metric: {e}", ok=False)
            )
            continue
        formatted = _format_scientific(value, row.format)
        results.append(
            CellResult(row.macro, formatted, source=row.run.path, ok=True)
        )

    sha = _git_sha(repo_root)
    timestamp = dt.datetime.now().isoformat(timespec="seconds")
    lines = [
        f"% Generated by scripts/reporting/build.py",
        f"% Artifact: {artifact.name}  (chapter {artifact.chapter})",
        f"% git: {sha}    generated_at: {timestamp}",
        "%",
    ]
    for r in results:
        lines.append(f"% {r.macro}  <-  {r.source}")
    lines.append("")
    for r in results:
        lines.append(rf"\newcommand{{{r.macro}}}{{{r.value}}}")
    lines.append("")
    return "\n".join(lines), results


def write_artifact(
    artifact: ReportArtifact, repo_root: Path, output_dir: Path
) -> list[CellResult]:
    content, results = render_macro_table(artifact, repo_root)
    target = output_dir / artifact.output_subpath
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    return results
