from __future__ import annotations

import datetime as dt
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .collect import MissingMetric, MissingRun, get_metric, load_metric_file, load_run
from .types import MetricFileRef, ReportArtifact, RunRef


TBD = r"\textit{TBD}"


@dataclass
class CellResult:
    macro: str
    value: str
    source: str  # human-readable: run path or "literal" or "missing: <reason>"
    ok: bool


def _format_flops(value: float) -> str:
    abs_value = abs(value)
    for scale, suffix in (
        (1e15, "PFLOPs"),
        (1e12, "TFLOPs"),
        (1e9, "GFLOPs"),
        (1e6, "MFLOPs"),
        (1e3, "KFLOPs"),
    ):
        if abs_value >= scale:
            return rf"\ensuremath{{{value / scale:.2f}\,\mathrm{{{suffix}}}}}"
    return rf"\ensuremath{{{value:.2f}\,\mathrm{{FLOPs}}}}"


def _format_scientific(value: float, fmt: str) -> str:
    """Format a float and rewrite Python's 'e' notation as LaTeX \\times 10^{...}.

    The result is wrapped in \\ensuremath{} so the macro can be used in either
    text or math mode in the chapter tables.
    """
    s = fmt.format(value)
    m = re.fullmatch(r"(-?\d+(?:\.\d+)?)[eE]([+-]?)0*(\d+)", s)
    if not m:
        return s
    mantissa, sign, exp_digits = m.groups()
    exp = ("-" if sign == "-" else "") + (exp_digits or "0")
    return rf"\ensuremath{{{mantissa}\times 10^{{{exp}}}}}"


def _format_value(value: float, fmt: str) -> str:
    if fmt == "flops":
        return _format_flops(value)
    return _format_scientific(value, fmt)


def _git_sha(repo_root: Path) -> str:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=repo_root, text=True
        )
        return out.strip()
    except Exception:
        return "unknown"


def _metric_keys(metric_key: str | list[str] | tuple[str, ...]) -> tuple[str, ...]:
    if isinstance(metric_key, str):
        return (metric_key,)
    return tuple(metric_key)


def render_macro_table(
    artifact: ReportArtifact, repo_root: Path, metrics_dir: Path | None = None
) -> tuple[str, list[CellResult]]:
    assert artifact.kind == "tex_macros"
    results: list[CellResult] = []
    for row in artifact.rows:
        if row.literal is not None:
            results.append(
                CellResult(row.macro, row.literal, source="literal", ok=True)
            )
            continue
        if row.run is None or row.metric_key is None:
            results.append(
                CellResult(row.macro, TBD, source="missing: no run/metric", ok=False)
            )
            continue
        try:
            if isinstance(row.run, RunRef):
                data = load_run(row.run, repo_root)
                source = row.run.path
            elif isinstance(row.run, MetricFileRef):
                if metrics_dir is None:
                    raise MissingRun("generated metrics dir unavailable")
                data = load_metric_file(row.run, metrics_dir)
                source = f"metrics/{row.run.path}"
            else:
                raise MissingRun(f"unsupported source: {row.run!r}")
            missing_keys: list[str] = []
            for key in _metric_keys(row.metric_key):
                try:
                    value = get_metric(data, key)
                    break
                except MissingMetric as e:
                    missing_keys.append(str(e))
            else:
                raise MissingMetric(" or ".join(missing_keys))
        except MissingRun as e:
            results.append(CellResult(row.macro, TBD, source=f"missing: {e}", ok=False))
            continue
        except MissingMetric as e:
            results.append(
                CellResult(row.macro, TBD, source=f"missing metric: {e}", ok=False)
            )
            continue
        formatted = _format_value(value, row.format)
        results.append(
            CellResult(row.macro, formatted, source=source, ok=True)
        )

    sha = _git_sha(repo_root)
    timestamp = dt.datetime.now().isoformat(timespec="seconds")
    lines = [
        f"% Generated by scripts/reporting/build.py",
        f"% Artifact: {artifact.name}  (chapter {artifact.chapter})",
        f"% git: {sha}    generated_at: {timestamp}",
        "%",
    ]
    for r in results:
        lines.append(f"% {r.macro}  <-  {r.source}")
    lines.append("")
    for r in results:
        lines.append(rf"\newcommand{{{r.macro}}}{{{r.value}}}")
    lines.append("")
    return "\n".join(lines), results


def write_artifact(
    artifact: ReportArtifact, repo_root: Path, output_dir: Path
) -> list[CellResult]:
    content, results = render_macro_table(
        artifact, repo_root, metrics_dir=output_dir / "metrics"
    )
    target = output_dir / artifact.output_subpath
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    return results
