model:
  backbone: "Factformer"
  args:
    loader: "ns"
    geotype: "structured_2D"
    task: "dynamic_autoregressive"
    space_dim: 2
    fun_dim: 10
    out_dim: 1
    n_hidden: 256
    n_heads: 8
    n_layers: 8
    mlp_ratio: 2
    unified_pos: 1
    ref: 8

training:
  batch_size: 2
  num_epochs: 500
  optimizer: "adamw"
  learning_rate: 0.001
  weight_decay: 1.0e-5
  scheduler: "OneCycleLR"
  pct_start: 0.3
  teacher_forcing: 1
